# Generated by Django 5.0.3 on 2024-03-20 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.IntegerField(blank=True, default=25400000000, max_length=15),
            preserve_default=False,
        ),
    ]
