# Generated by Django 5.0.3 on 2024-03-22 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_alter_user_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
    ]
