# Generated by Django 5.0.3 on 2024-03-23 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tickets', '0004_ticket_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='phone_number',
            field=models.CharField(blank=True, default=254740488461, max_length=15),
        ),
    ]
